version: '3'
services:
  go-server:
    networks:
        - service-net
    image: "gocd/gocd-server:v21.2.0"  
    ports:    
        - "8153:8153"
        - "8154:8154"                    
  go-agent: 
    networks:
        - service-net
    image: "gocd/gocd-agent-ubuntu-16.04:v21.2.0"
    depends_on:
        - go-server      
    environment:
        GO_SERVER_URL: "http://go-server:8153/go"        
networks:
    service-net: